# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "pip"
    directories:
      - "/"
      - "/plugins/yls-yara"
      - "/pytest-yls"
    schedule:
      interval: "daily"
    versioning-strategy: increase
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"
  - package-ecosystem: "npm"
    directory: "/editors/vscode"
    schedule:
      interval: "daily"
    versioning-strategy: increase
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"
